// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pptbgyoudlqlridoltpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdGJneW91ZGxxbHJpZG9sdHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDE4MTksImV4cCI6MjA3MzQxNzgxOX0.whpPavsiCgr6iPp3dQXfHQzVG0KnnDvFlSyysIhIVNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});